### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by nesbox** [mtasic85/quickjs-env#2]
Hi @mtasic85 

I am getting `TypeError: 'type' object is not subscriptable` error when I try to call `./qjs-cffi -h`

``` bash
~/qjstest$ ./qjs-cffi -h
Traceback (most recent call last):
  File "local/quickjs-cffi/autogen.py", line 87, in <module>
    class CParser:
  File "local/quickjs-cffi/autogen.py", line 203, in CParser
    def pop_processing_context(self) -> dict[str, list[dict]]:
TypeError: 'type' object is not subscriptable
```

Could you please help me get it running? It's a very interesting idea to create modules for QuickJS using FFI.
Thank you.

**Comment by mtasic85** [comment]
Hi @nesbox

Make sure that you use python 3.10.

**Comment by nesbox** [comment]
Just installed Python 3.10
```bash
~/qjstest$ python --version
Python 3.10.7
```
Got the same error, unfortunately I'm not familiar with Python :(

**Comment by nesbox** [comment]
I tried all the Python versions without success :(
Any other ideas?
